USE DB_BIBLIOTECA;

CREATE TABLE CATEGORIA (
  IdCategoria INT PRIMARY KEY AUTO_INCREMENT,
  Descripcion VARCHAR(50),
  Estado BIT DEFAULT 1,
  FechaCreacion DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE EDITORIAL (
  IdEditorial INT PRIMARY KEY AUTO_INCREMENT,
  Descripcion VARCHAR(50),
  Estado BIT DEFAULT 1,
  FechaCreacion DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE AUTOR (
  IdAutor INT PRIMARY KEY AUTO_INCREMENT,
  Descripcion VARCHAR(50),
  Estado BIT DEFAULT 1,
  FechaCreacion DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE LIBRO (
  IdLibro INT PRIMARY KEY AUTO_INCREMENT,
  Titulo VARCHAR(100),
  RutaPortada VARCHAR(100),
  NombrePortada VARCHAR(100),
  IdAutor INT,
  IdCategoria INT,
  IdEditorial INT,
  Ubicacion VARCHAR(50),
  Ejemplares INT,
  Estado BIT DEFAULT 1,
  FechaCreacion DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (IdAutor) REFERENCES AUTOR(IdAutor),
  FOREIGN KEY (IdCategoria) REFERENCES CATEGORIA(IdCategoria),
  FOREIGN KEY (IdEditorial) REFERENCES EDITORIAL(IdEditorial)
);

CREATE TABLE TIPO_PERSONA (
  IdTipoPersona INT PRIMARY KEY,
  Descripcion VARCHAR(50),
  Estado BIT DEFAULT 1,
  FechaCreacion DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PERSONA (
  IdPersona INT PRIMARY KEY AUTO_INCREMENT,
  Nombre VARCHAR(50),
  Apellido VARCHAR(50),
  Correo VARCHAR(50),
  Clave VARCHAR(50),
  Codigo VARCHAR(50),
  IdTipoPersona INT,
  Estado BIT DEFAULT 1,
  FechaCreacion DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (IdTipoPersona) REFERENCES TIPO_PERSONA(IdTipoPersona)
);

CREATE TABLE ESTADO_PRESTAMO (
  IdEstadoPrestamo INT PRIMARY KEY,
  Descripcion VARCHAR(50),
  Estado BIT DEFAULT 1,
  FechaCreacion DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PRESTAMO (
  IdPrestamo INT PRIMARY KEY AUTO_INCREMENT,
  IdEstadoPrestamo INT,
  IdPersona INT,
  IdLibro INT,
  FechaDevolucion DATETIME,
  FechaConfirmacionDevolucion DATETIME,
  EstadoEntregado VARCHAR(100),
  EstadoRecibido VARCHAR(100),
  Estado BIT DEFAULT 1,
  FechaCreacion DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (IdEstadoPrestamo) REFERENCES ESTADO_PRESTAMO(IdEstadoPrestamo),
  FOREIGN KEY (IdPersona) REFERENCES PERSONA(IdPersona),
  FOREIGN KEY (IdLibro) REFERENCES LIBRO(IdLibro)
);